"""add gateway control plane state

Revision ID: 3a12bef2c45c
Revises: d737c231b0eb
Create Date: 2026-09-03 01:33:45.316262
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a12bef2c45c"
down_revision: str | Sequence[str] | None = "d737c231b0eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrolment_tokens",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("token_digest", sa.String(length=128), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("requested_scopes", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_principal_id", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(
        op.f("ix_enrolment_tokens_expires_at"),
        "enrolment_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrolment_tokens_principal_id"),
        "enrolment_tokens",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrolment_tokens_tenant_id"),
        "enrolment_tokens",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "quota_windows",
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_seconds", sa.Integer(), nullable=False),
        sa.Column("reserved_count", sa.Integer(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "window_start", "period_seconds"),
    )
    op.create_table(
        "mcp_session_affinities",
        sa.Column("session_digest", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("backend_id", sa.String(length=48), nullable=False),
        sa.Column("corpus_version", sa.String(length=128), nullable=False),
        sa.Column("capability_id", sa.String(length=48), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backend_id"],
            ["scholar_backends.id"],
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["dsh_capabilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("session_digest"),
    )
    op.create_index(
        op.f("ix_mcp_session_affinities_backend_id"),
        "mcp_session_affinities",
        ["backend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_session_affinities_capability_id"),
        "mcp_session_affinities",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_session_affinities_expires_at"),
        "mcp_session_affinities",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mcp_session_affinities_tenant_id"),
        "mcp_session_affinities",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "audit_events", sa.Column("capability_id", sa.String(length=48), nullable=True)
    )
    op.add_column(
        "audit_events",
        sa.Column("mcp_session_digest", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "audit_events", sa.Column("tool_name", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "audit_events",
        sa.Column("argument_digest", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "audit_events", sa.Column("backend_id", sa.String(length=48), nullable=True)
    )
    op.add_column(
        "audit_events",
        sa.Column("corpus_version", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "audit_events", sa.Column("decision", sa.String(length=32), nullable=True)
    )
    op.add_column("audit_events", sa.Column("latency_ms", sa.Integer(), nullable=True))
    op.add_column(
        "audit_events", sa.Column("result_class", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "audit_events", sa.Column("returned_bytes", sa.Integer(), nullable=True)
    )
    op.add_column("audit_events", sa.Column("quota_delta", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_audit_events_backend_id"), "audit_events", ["backend_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_capability_id"),
        "audit_events",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_decision"), "audit_events", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_mcp_session_digest"),
        "audit_events",
        ["mcp_session_digest"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_tool_name"), "audit_events", ["tool_name"], unique=False
    )
    with op.batch_alter_table("dsh_capabilities") as batch_op:
        batch_op.add_column(
            sa.Column(
                "issued_from_enrolment_id",
                sa.String(length=48),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("session_label", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(
            op.f("ix_dsh_capabilities_issued_from_enrolment_id"),
            ["issued_from_enrolment_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_dsh_capabilities_enrolment",
            "enrolment_tokens",
            ["issued_from_enrolment_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dsh_capabilities") as batch_op:
        batch_op.drop_constraint(
            "fk_dsh_capabilities_enrolment",
            type_="foreignkey",
        )
        batch_op.drop_index(
            op.f("ix_dsh_capabilities_issued_from_enrolment_id"),
        )
        batch_op.drop_column("last_used_at")
        batch_op.drop_column("session_label")
        batch_op.drop_column("issued_from_enrolment_id")
    op.drop_index(op.f("ix_audit_events_tool_name"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_mcp_session_digest"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_decision"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_capability_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_backend_id"), table_name="audit_events")
    op.drop_column("audit_events", "quota_delta")
    op.drop_column("audit_events", "returned_bytes")
    op.drop_column("audit_events", "result_class")
    op.drop_column("audit_events", "latency_ms")
    op.drop_column("audit_events", "decision")
    op.drop_column("audit_events", "corpus_version")
    op.drop_column("audit_events", "backend_id")
    op.drop_column("audit_events", "argument_digest")
    op.drop_column("audit_events", "tool_name")
    op.drop_column("audit_events", "mcp_session_digest")
    op.drop_column("audit_events", "capability_id")
    op.drop_index(
        op.f("ix_mcp_session_affinities_tenant_id"), table_name="mcp_session_affinities"
    )
    op.drop_index(
        op.f("ix_mcp_session_affinities_expires_at"),
        table_name="mcp_session_affinities",
    )
    op.drop_index(
        op.f("ix_mcp_session_affinities_capability_id"),
        table_name="mcp_session_affinities",
    )
    op.drop_index(
        op.f("ix_mcp_session_affinities_backend_id"),
        table_name="mcp_session_affinities",
    )
    op.drop_table("mcp_session_affinities")
    op.drop_table("quota_windows")
    op.drop_index(op.f("ix_enrolment_tokens_tenant_id"), table_name="enrolment_tokens")
    op.drop_index(
        op.f("ix_enrolment_tokens_principal_id"), table_name="enrolment_tokens"
    )
    op.drop_index(op.f("ix_enrolment_tokens_expires_at"), table_name="enrolment_tokens")
    op.drop_table("enrolment_tokens")
    # ### end Alembic commands ###
