"""enforce gateway quotas

Revision ID: 4a4328e1b931
Revises: e87fa9c478bf
Create Date: 2026-09-03 02:53:16.182049
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a4328e1b931"
down_revision: str | Sequence[str] | None = "e87fa9c478bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quota_reservations",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'failed')",
            name="ck_quota_reservation_status",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_quota_reservations_active_expiry",
        "quota_reservations",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quota_reservations_tenant_id"),
        "quota_reservations",
        ["tenant_id"],
        unique=False,
    )
    with op.batch_alter_table("quota_policies") as batch_op:
        batch_op.add_column(
            sa.Column(
                "concurrency_limit",
                sa.Integer(),
                server_default=sa.text("1"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "enforcement_enabled",
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch_op.create_check_constraint(
            "ck_quota_policy_concurrency_limit",
            "concurrency_limit > 0",
        )
        batch_op.create_check_constraint(
            "ck_quota_policy_period",
            "period_seconds > 0",
        )
        batch_op.create_check_constraint(
            "ck_quota_policy_request_limit",
            "request_limit > 0",
        )
    with op.batch_alter_table("quota_windows") as batch_op:
        batch_op.add_column(
            sa.Column(
                "active_count",
                sa.Integer(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quota_windows") as batch_op:
        batch_op.drop_column("active_count")
    with op.batch_alter_table("quota_policies") as batch_op:
        batch_op.drop_constraint(
            "ck_quota_policy_request_limit",
            type_="check",
        )
        batch_op.drop_constraint(
            "ck_quota_policy_period",
            type_="check",
        )
        batch_op.drop_constraint(
            "ck_quota_policy_concurrency_limit",
            type_="check",
        )
        batch_op.drop_column("enforcement_enabled")
        batch_op.drop_column("concurrency_limit")
    op.drop_index(
        op.f("ix_quota_reservations_tenant_id"),
        table_name="quota_reservations",
    )
    op.drop_index(
        "ix_quota_reservations_active_expiry",
        table_name="quota_reservations",
    )
    op.drop_table("quota_reservations")
    # ### end Alembic commands ###
