"""create control plane tables

Revision ID: d737c231b0eb
Revises:
Create Date: 2026-09-02 15:52:37.421085
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d737c231b0eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=96), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=True),
        sa.Column("tenant_id", sa.String(length=48), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=96), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_occurred_at_id",
        "audit_events",
        ["occurred_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_principal_id"),
        "audit_events",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False
    )
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(
            """
            CREATE FUNCTION reject_audit_event_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit events are append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_reject_update
            BEFORE UPDATE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_reject_delete
            BEFORE DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation()
            """
        )
    elif dialect == "sqlite":
        op.execute(
            """
            CREATE TRIGGER audit_events_reject_update
            BEFORE UPDATE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit events are append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_reject_delete
            BEFORE DELETE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit events are append-only');
            END
            """
        )
    op.create_table(
        "oidc_login_states",
        sa.Column("state_digest", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        sa.Column("code_verifier", sa.String(length=128), nullable=False),
        sa.Column("return_to", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("state_digest"),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject", name="uq_principal_issuer_subject"),
    )
    op.create_table(
        "scholar_backends",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("corpus_version", sa.String(length=128), nullable=False),
        sa.Column("credential_ref", sa.String(length=512), nullable=False),
        sa.Column("credential_version", sa.String(length=128), nullable=True),
        sa.Column("credential_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("capacity", sa.JSON(), nullable=False),
        sa.Column("last_probe_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_probe_ready", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "browser_sessions",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("csrf_digest", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_browser_sessions_principal_id"),
        "browser_sessions",
        ["principal_id"],
        unique=False,
    )
    op.create_table(
        "dsh_capabilities",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("token_digest", sa.String(length=128), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(
        op.f("ix_dsh_capabilities_principal_id"),
        "dsh_capabilities",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dsh_capabilities_tenant_id"),
        "dsh_capabilities",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_digest", sa.String(length=128), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "principal_id",
            "operation",
            "key",
            name="uq_idempotency_principal_operation_key",
        ),
    )
    op.create_table(
        "quota_policies",
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("quota_class", sa.String(length=64), nullable=False),
        sa.Column("request_limit", sa.Integer(), nullable=False),
        sa.Column("period_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "role_bindings",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "principal_id", "tenant_id", "role", name="uq_role_binding"
        ),
    )
    op.create_index(
        op.f("ix_role_bindings_principal_id"),
        "role_bindings",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_bindings_tenant_id"), "role_bindings", ["tenant_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_team_tenant_name"),
    )
    op.create_index(op.f("ix_teams_tenant_id"), "teams", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_routes",
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("backend_id", sa.String(length=48), nullable=False),
        sa.Column("corpus_version", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backend_id"],
            ["scholar_backends.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_index(
        op.f("ix_tenant_routes_backend_id"),
        "tenant_routes",
        ["backend_id"],
        unique=False,
    )
    op.create_table(
        "tool_policies",
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("allowed_tools", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=48), nullable=False),
        sa.Column("tenant_id", sa.String(length=48), nullable=False),
        sa.Column("team_id", sa.String(length=48), nullable=True),
        sa.Column("principal_id", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "team_id", "principal_id", name="uq_membership_scope_principal"
        ),
    )
    op.create_index(
        op.f("ix_memberships_principal_id"),
        "memberships",
        ["principal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memberships_team_id"), "memberships", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_memberships_tenant_id"), "memberships", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_events_reject_delete ON audit_events")
        op.execute("DROP TRIGGER IF EXISTS audit_events_reject_update ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS reject_audit_event_mutation()")
    elif dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS audit_events_reject_delete")
        op.execute("DROP TRIGGER IF EXISTS audit_events_reject_update")
    op.drop_index(op.f("ix_memberships_tenant_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_team_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_principal_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("tool_policies")
    op.drop_index(op.f("ix_tenant_routes_backend_id"), table_name="tenant_routes")
    op.drop_table("tenant_routes")
    op.drop_index(op.f("ix_teams_tenant_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_role_bindings_tenant_id"), table_name="role_bindings")
    op.drop_index(op.f("ix_role_bindings_principal_id"), table_name="role_bindings")
    op.drop_table("role_bindings")
    op.drop_table("quota_policies")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_dsh_capabilities_tenant_id"), table_name="dsh_capabilities")
    op.drop_index(
        op.f("ix_dsh_capabilities_principal_id"), table_name="dsh_capabilities"
    )
    op.drop_table("dsh_capabilities")
    op.drop_index(
        op.f("ix_browser_sessions_principal_id"), table_name="browser_sessions"
    )
    op.drop_table("browser_sessions")
    op.drop_table("tenants")
    op.drop_table("scholar_backends")
    op.drop_table("principals")
    op.drop_table("oidc_login_states")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_principal_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at_id", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
