"""make role bindings revocable

Revision ID: e87fa9c478bf
Revises: 3a12bef2c45c
Create Date: 2026-09-03 01:50:23.693887
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e87fa9c478bf"
down_revision: str | Sequence[str] | None = "3a12bef2c45c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enrolment_tokens",
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    op.add_column(
        "role_bindings",
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "role_bindings",
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_bindings", "version")
    op.drop_column("role_bindings", "revoked_at")
    op.drop_column("enrolment_tokens", "version")
    # ### end Alembic commands ###
